# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Labyrinthine Wanderings
email: wanderings [at] wander [dot] ingstar [dot] com
description: > # this means to ignore newlines until "baseurl:"
  Aneel's musings on code and tech
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wanderingstar.github.io" # the base hostname & protocol for your site
twitter_username: _aneel_
github_username:  WanderingStar

# Build settings
markdown: kramdown
